# -*- coding: utf-8 -*-
"""ImageForWHT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GomVEmZq3Wz5TJ9HgPgHYx_Ys0PMJmCQ
"""

from google.colab import files
from PIL import Image
import numpy as np
from scipy.linalg import hadamard
import matplotlib.pyplot as plt
import io

#uploading images
uploaded = files.upload()
filename = list(uploaded.keys())[0]

img = Image.open(io.BytesIO(uploaded[filename])).convert("L")
arr = np.array(img)

print("Image shape:", arr.shape)

#selecting a 8x8 block
row, col = 100, 100
block = arr[row:row+8, col:col+8]

print("\nOriginal 8x8 Block:\n")
print(block)

#centering data because i need it signed and not from 0 to 255
block_signed = block.astype(int) - 128

print("\nCentered Block (RTL input):\n")
print(block_signed)

#THE SYSTEMVERILOG INPUT STIMULUS THAT SHLD BE GIVEN TO SV TB
print("\nSystemVerilog assignments:\n")

for i in range(8):
    for j in range(8):
        val = int(block_signed[i][j])  # ensure python int

        if val < 0:
            print(f"x_in[{i}][{j}] = -8'sd{abs(val)};", end=" ")
        else:
            print(f"x_in[{i}][{j}] = 8'sd{val};", end=" ")
    print()   # new line per row

#computing WHT
H = hadamard(8)
wht = H @ block_signed @ H

print("\nPython WHT Output :\n")
print(wht)

#plotting of image and visualization
plt.imshow(block_signed, cmap='gray')
plt.title("Centered Input Block")
plt.colorbar()
plt.show()

plt.imshow(np.abs(wht), cmap='hot')
plt.title("WHT Magnitude")
plt.colorbar()
plt.show()